/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade;

import javax.swing.JFileChooser;

/**
 *
 * @author deciodecarvalho
 */
public class TelaOpenFile extends javax.swing.JFrame {

    /**
     * Creates new form JInternalFrameFile
     */
    public TelaOpenFile() {
        initComponents();
        jFileChooser1.addChoosableFileFilter(new TextFilter());

        int retVal;

        //JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.addChoosableFileFilter(new TextFilter());

        retVal = jFileChooser1.showOpenDialog(this);

        if (retVal == JFileChooser.APPROVE_OPTION) {
            System.out.println(jFileChooser1.getSelectedFile().getAbsolutePath());

            System.out.println(jFileChooser1.getSelectedFile().getName());
        }

                
        this.dispose();
        this.setVisible(true);
        jFileChooser1.setVisible(false);
    }

    /*
     public void actionPerformed(ActionEvent e) {
     int retVal;

     //JFileChooser jFileChooser1 = new JFileChooser();
     jFileChooser1.addChoosableFileFilter(new TextFilter());
     retVal = jFileChooser1.showOpenDialog(this);

     if (retVal == JFileChooser.APPROVE_OPTION) {
     System.out.println(jFileChooser1.getSelectedFile().getName());
     }
     }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setName("telaFile"); // NOI18N

        jFileChooser1.setFileFilter(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jFileChooser1.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
